WITH T1 AS (
SELECT
    PLATFORM AS "DEP_ENT",
	DATE_TRUNC('month', TRX_DATE) AS "MONTH", 
	SUM(NET_SALES) AS "NET_SALES"
FROM ANALYTICS.SALES."sales_summary_v"
WHERE DATE_TRUNC('month', TRX_DATE) < '2020-01-01'
    AND TYPE IN ('INV', 'CM', 'DM')
GROUP BY 
	ALL 
UNION
--after 2020
(SELECT 
    PLATFORM AS "DEP_ENT",
	DATE_TRUNC('month', TRX_DATE) AS "MONTH", 
	SUM(NET_SALES) AS "NET_SALES"
FROM ANALYTICS.SALES."sales_summary_v"
WHERE DATE_TRUNC('month', TRX_DATE) >= '2020-01-01'
GROUP BY 
	ALL) )
SELECT *
FROM T1 
-- dep-ent combinations with budget
WHERE MONTH >= '2016-01-01' AND
    DEP_ENT IS NOT NULL