SELECT
    DEPARTMENT,
    BU_ENTITY,
    DEPARTMENT || '_' || BU_ENTITY AS "DEP_ENT",
	DATE_TRUNC('month', TRX_DATE) AS "MONTH", 
	SUM(NET_SALES) AS "NET_SALES"
FROM ANALYTICS.SALES."sales_summary_v"
WHERE BU_ENTITY IN ('155', '310', '165')
    AND DATE_TRUNC('month', TRX_DATE) < '2020-01-01'
    AND TYPE IN ('INV', 'CM', 'DM')
GROUP BY 
	ALL 
UNION
--after 2020
(SELECT 
    DEPARTMENT,
    BU_ENTITY,
    DEPARTMENT || '_' || BU_ENTITY AS "DEP_ENT",
	DATE_TRUNC('month', TRX_DATE) AS "MONTH", 
	SUM(NET_SALES) AS "NET_SALES"
FROM ANALYTICS.SALES."sales_summary_v"
WHERE BU_ENTITY IN ('155', '310', '165')
    AND DATE_TRUNC('month', TRX_DATE) >= '2020-01-01'
GROUP BY 
	ALL)